
version: "3"

services:

  splunk-network-health-check:
    build:
      context: .
    restart: "unless-stopped"
    privileged: true
    volumes:
      - .:/mnt
      - ./splunk-data:/data
    ports:
      - 8000:8000


